export const state = {
	themeColor:'#fff',
	isShowFooter:true,
	footer_tab:0,
	secondNavData:[],
	subConData:[],
	subNavData:[],
	host:'http://testadmin.zhinengdayi.com',
	// host:'http://zhinengdayi.com',
	talkHost:'http://123.56.177.92:3000',
	// talkHost:'http://zhinengdayi.com:3000',
	imgHost: 'http://testimg.zhinengdayi.com',
	//imgHost: 'img.zhinengdayi.com',
    baseUrl:'/weixin/api',
    wendaUrl:'/weixin/api',
	scode:'',
	timeout:200,
	contentType:2,
	infoId:0,
	catId: 0,
	isLogin:sessionStorage.getItem('isLogin')?Number(sessionStorage.getItem('isLogin')):0,
	messageCount:0,
	scholl:null,
	allSchoolInfo:{},
	footerMenu:[],
	loadingFlag:true,
    wxHost:'http://test.rocklee.com.cn', //微信服务端域名
    // wxHost:'http://weixin.zhinengdayi.com', //微信服务端域名
	identify:'',
	sid:0,
	schListTab: 1,
	sdecode:false,
	sdecode2:false,
	currentHref : '',
	collectedSchNum: 0,
	searchHistoryArr: [],
	showFilter: false,
	filterProvince: '',
	filterShcool: '',
	filterRecruit: '',
	searchKeyword: '',
    mVersion:sessionStorage.getItem('mVersion')?sessionStorage.getItem('mVersion'):'',
	viewSourceUrl:document.referrer
}
