
export const SET_CONTENT_TO_AUDIT_NUM='SET_CONTENT_TO_AUDIT_NUM';

export const SET_ANSWER_TO_AUDIT_NUM='SET_ANSWER_TO_AUDIT_NUM';

export const SET_QUESTION_TO_DEAL_NUM='SET_QUESTION_TO_DEAL_NUM';

export const SET_LOGINNAME='SET_LOGINNAME';

export const SET_REALNAME='SET_REALNAME';

export const SET_SCODE='SET_SCODE';

export const SET_SCHOOL_LOGO='SET_SCHOOL_LOGO';

export const SET_ENTRY_INDEX='SET_ENTRY_INDEX';

export const SET_LOADING_STATU='SET_LOADING_STATU';



//首页的3个未读数据
export const SET_CONTENT_NOT_READ_NUM='SET_CONTENT_NOT_READ_NUM';

export const SET_ANSWER_NOT_READ_NUM='SET_ANSWER_NOT_READ_NUM';

export const SET_QUESTION_NOT_READ_NUM='SET_QUESTION_NOT_READ_NUM';

//快捷答疑列表页的4个未读数据
export const SET_WAIT_CLAIM_NOT_READ_NUM='SET_WAIT_CLAIM_NOT_READ_NUM';

export const SET_WAIT_REPLY_NOT_READ_NUM='SET_WAIT_REPLY_NOT_READ_NUM';

export const SET_HAS_RESOLVE_NOT_READ_NUM='SET_HAS_RESOLVE_NOT_READ_NUM';

export const SET_REJECT_REPLY_NOT_READ_NUM='SET_REJECT_REPLY_NOT_READ_NUM';


//控制自动登录到首页后能否后退到登录页    防止后退回弹
export const SET_ENTRY_STATUS='SET_ENTRY_STATUS';

export const SET_CURRENT_CLASSIFY='SET_CURRENT_CLASSIFY';

export const SET_LOGIN_CODE='SET_LOGIN_CODE';






